#!/usr/bin/env python3

import sys

f = open(sys.argv[1], "r")

lines = f.readlines()

symbolTable = { }

counter = 0

while counter < len(lines):
    line = lines[counter]
    counter = counter + 1

    if "$DEFINE" in line and "'" not in line  and '"' not in line:
        line = line.strip()
        _, symbol = line.split(" ")
        symbolTable[symbol] = True
        continue

    if "$IFDEF" in line and "'" not in line  and '"' not in line:
        line = line.strip()
        _, symbol = line.split(" ")
        if symbol in symbolTable:
            continue
        line = lines[counter]
        stack = 1
        while stack != 0:
            if "$IFDEF" in line and "'" not in line  and '"' not in line:
                stack = stack + 1
            if "$ENDIF" in line and "'" not in line  and '"' not in line:
                stack = stack - 1
            counter = counter + 1
            line = lines[counter]
        continue

    if "$ENDIF" in line and "'" not in line  and '"' not in line:
        continue

    print(line[:-1])

f.close()
